<?xml version="1.0" encoding="utf-8"?>
<Database Name="webdoantruong" Class="LinQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MANTERO-81F34CE\SQLEXPRESS;Initial Catalog=webdoantruong;Integrated Security=True" SettingsObjectName="DTOAuction.Properties.Settings" SettingsPropertyName="nuocmamConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ALBUM" Member="ALBUMs">
    <Type Name="ALBUM">
      <Column Name="maalbum" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenalbum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGBAO" Member="THONGBAOs">
    <Type Name="THONGBAO">
      <Column Name="mathongbao" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BAIHAT" Member="BAIHATs">
    <Type Name="BAIHAT">
      <Column Name="mabaihat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenbaihat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="linkbaihat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BAIVIET" Member="BAIVIETs">
    <Type Name="BAIVIET">
      <Column Name="mabaiviet" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="maloaibaiviet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CAUHOIKHAOSAT" Member="CAUHOIKHAOSATs">
    <Type Name="CAUHOIKHAOSAT">
      <Column Name="macauhoikhaosat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="lock" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHUYENMUC" Member="CHUYENMUCs">
    <Type Name="CHUYENMUC">
      <Column Name="machuyenmuc" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenchuyenmuc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANGKYHOATDONG" Member="DANGKYHOATDONGs">
    <Type Name="DANGKYHOATDONG">
      <Column Name="madangky" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thamgia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DANGKYMUONPHONG" Member="DANGKYMUONPHONGs">
    <Type Name="DANGKYMUONPHONG">
      <Column Name="madangky" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mucdich" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="donvimuon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DAPANKHAOSAT" Member="DAPANKHAOSATs">
    <Type Name="DAPANKHAOSAT">
      <Column Name="madapankhaosat" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="makhaosat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIOITHIEU" Member="GIOITHIEUs">
    <Type Name="GIOITHIEU">
      <Column Name="magioithieu" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tengioithieu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.HETHONGTOCHUC" Member="HETHONGTOCHUCs">
    <Type Name="HETHONGTOCHUC">
      <Column Name="mahethongtochuc" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenhethongtochuc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.HINHANH" Member="HINHANHs">
    <Type Name="HINHANH">
      <Column Name="mahinhanh" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="hinhanh" Member="hinhanh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="maalbum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOATDONG" Member="HOATDONGs">
    <Type Name="HOATDONG">
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenhoatdong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ngaydienra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maloaihoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoigianbatdaudangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thoigianketthucdangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHAOSAT" Member="KHAOSATs">
    <Type Name="KHAOSAT">
      <Column Name="macauhoi" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="madapan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LICHLAMVIEC" Member="LICHLAMVIECs">
    <Type Name="LICHLAMVIEC">
      <Column Name="noidung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIBAIVIET" Member="LOAIBAIVIETs">
    <Type Name="LOAIBAIVIET">
      <Column Name="maloaibaiviet" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenloaibaiviet" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="machuyenmuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIHOATDONG" Member="LOAIHOATDONGs">
    <Type Name="LOAIHOATDONG">
      <Column Name="maloaihoatdong" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenloaihoatdong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIVAITRO" Member="LOAIVAITROs">
    <Type Name="LOAIVAITRO">
      <Column Name="maloaivaitro" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tenloaivaitro" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SINHVIEN" Member="SINHVIENs">
    <Type Name="SINHVIEN">
      <Column Name="masinhvien" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="vaitro" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TAPTIN" Member="TAPTINs">
    <Type Name="TAPTIN">
      <Column Name="mataptin" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="tentaptin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="duongdan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="mabaiviet" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.ALBUM_add" Method="ALBUM_add">
    <Parameter Name="maalbum" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenalbum" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THONGBAO_update" Method="THONGBAO_update">
    <Parameter Name="mathongbao" Type="System.Int32" DbType="Int" />
    <Parameter Name="tieude" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="noidung" Type="System.String" DbType="NText" />
    <Parameter Name="mahoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaydang" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ALBUM_delete" Method="ALBUM_delete">
    <Parameter Name="maalbum" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ALBUM_get" Method="ALBUM_get">
    <Parameter Name="maalbum" Type="System.Int32" DbType="Int" />
    <ElementType Name="ALBUM_getResult">
      <Column Name="maalbum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenalbum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ALBUM_getall" Method="ALBUM_getall">
    <ElementType Name="ALBUM_getallResult">
      <Column Name="maalbum" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenalbum" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ALBUM_getpaged" Method="ALBUM_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.ALBUM_update" Method="ALBUM_update">
    <Parameter Name="maalbum" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenalbum" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BAIHAT_add" Method="BAIHAT_add">
    <Parameter Name="mabaihat" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenbaihat" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="linkbaihat" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BAIHAT_delete" Method="BAIHAT_delete">
    <Parameter Name="mabaihat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BAIHAT_get" Method="BAIHAT_get">
    <Parameter Name="mabaihat" Type="System.Int32" DbType="Int" />
    <ElementType Name="BAIHAT_getResult">
      <Column Name="mabaihat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenbaihat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="linkbaihat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BAIHAT_getall" Method="BAIHAT_getall">
    <ElementType Name="BAIHAT_getallResult">
      <Column Name="mabaihat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenbaihat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="linkbaihat" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BAIHAT_getpaged" Method="BAIHAT_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BAIHAT_update" Method="BAIHAT_update">
    <Parameter Name="mabaihat" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenbaihat" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="linkbaihat" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BAIVIET_add" Method="BAIVIET_add">
    <Parameter Name="mabaiviet" Type="System.Int32" DbType="Int" />
    <Parameter Name="tieude" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="noidung" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="maloaibaiviet" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaydang" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BAIVIET_delete" Method="BAIVIET_delete">
    <Parameter Name="mabaiviet" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BAIVIET_get" Method="BAIVIET_get">
    <Parameter Name="mabaiviet" Type="System.Int32" DbType="Int" />
    <ElementType Name="BAIVIET_getResult">
      <Column Name="mabaiviet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="maloaibaiviet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BAIVIET_getall" Method="BAIVIET_getall">
    <ElementType Name="BAIVIET_getallResult">
      <Column Name="mabaiviet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="maloaibaiviet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BAIVIET_getpaged" Method="BAIVIET_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BAIVIET_update" Method="BAIVIET_update">
    <Parameter Name="mabaiviet" Type="System.Int32" DbType="Int" />
    <Parameter Name="tieude" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="noidung" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="maloaibaiviet" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaydang" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAUHOIKHAOSAT_add" Method="CAUHOIKHAOSAT_add">
    <Parameter Name="macauhoikhaosat" Type="System.Int32" DbType="Int" />
    <Parameter Name="tieude" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="lock" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAUHOIKHAOSAT_delete" Method="CAUHOIKHAOSAT_delete">
    <Parameter Name="macauhoikhaosat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAUHOIKHAOSAT_get" Method="CAUHOIKHAOSAT_get">
    <Parameter Name="macauhoikhaosat" Type="System.Int32" DbType="Int" />
    <ElementType Name="CAUHOIKHAOSAT_getResult">
      <Column Name="macauhoikhaosat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="lock" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CAUHOIKHAOSAT_getall" Method="CAUHOIKHAOSAT_getall">
    <ElementType Name="CAUHOIKHAOSAT_getallResult">
      <Column Name="macauhoikhaosat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="lock" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CAUHOIKHAOSAT_getpaged" Method="CAUHOIKHAOSAT_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CAUHOIKHAOSAT_update" Method="CAUHOIKHAOSAT_update">
    <Parameter Name="macauhoikhaosat" Type="System.Int32" DbType="Int" />
    <Parameter Name="tieude" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="lock" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CHUYENMUC_add" Method="CHUYENMUC_add">
    <Parameter Name="machuyenmuc" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenchuyenmuc" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CHUYENMUC_delete" Method="CHUYENMUC_delete">
    <Parameter Name="machuyenmuc" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CHUYENMUC_get" Method="CHUYENMUC_get">
    <Parameter Name="machuyenmuc" Type="System.Int32" DbType="Int" />
    <ElementType Name="CHUYENMUC_getResult">
      <Column Name="machuyenmuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenchuyenmuc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CHUYENMUC_getall" Method="CHUYENMUC_getall">
    <ElementType Name="CHUYENMUC_getallResult">
      <Column Name="machuyenmuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenchuyenmuc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CHUYENMUC_getpaged" Method="CHUYENMUC_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CHUYENMUC_update" Method="CHUYENMUC_update">
    <Parameter Name="machuyenmuc" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenchuyenmuc" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DANGKYHOATDONG_add" Method="DANGKYHOATDONG_add">
    <Parameter Name="madangky" Type="System.Int32" DbType="Int" />
    <Parameter Name="masinhvien" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mahoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaydangky" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="thamgia" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DANGKYHOATDONG_delete" Method="DANGKYHOATDONG_delete">
    <Parameter Name="madangky" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DANGKYHOATDONG_get" Method="DANGKYHOATDONG_get">
    <Parameter Name="madangky" Type="System.Int32" DbType="Int" />
    <ElementType Name="DANGKYHOATDONG_getResult">
      <Column Name="madangky" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thamgia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DANGKYHOATDONG_getall" Method="DANGKYHOATDONG_getall">
    <ElementType Name="DANGKYHOATDONG_getallResult">
      <Column Name="madangky" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thamgia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DANGKYHOATDONG_getpaged" Method="DANGKYHOATDONG_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DANGKYHOATDONG_update" Method="DANGKYHOATDONG_update">
    <Parameter Name="madangky" Type="System.Int32" DbType="Int" />
    <Parameter Name="masinhvien" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="mahoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaydangky" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="thamgia" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DANGKYMUONPHONG_add" Method="DANGKYMUONPHONG_add">
    <Parameter Name="madangky" Type="System.Int32" DbType="Int" />
    <Parameter Name="masinhvien" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngay" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Parameter Name="mucdich" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="donvimuon" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DANGKYMUONPHONG_delete" Method="DANGKYMUONPHONG_delete">
    <Parameter Name="madangky" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DANGKYMUONPHONG_get" Method="DANGKYMUONPHONG_get">
    <Parameter Name="madangky" Type="System.Int32" DbType="Int" />
    <ElementType Name="DANGKYMUONPHONG_getResult">
      <Column Name="madangky" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mucdich" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="donvimuon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DANGKYMUONPHONG_getall" Method="DANGKYMUONPHONG_getall">
    <ElementType Name="DANGKYMUONPHONG_getallResult">
      <Column Name="madangky" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ngay" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="mucdich" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="donvimuon" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DANGKYMUONPHONG_getpaged" Method="DANGKYMUONPHONG_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DANGKYMUONPHONG_update" Method="DANGKYMUONPHONG_update">
    <Parameter Name="madangky" Type="System.Int32" DbType="Int" />
    <Parameter Name="masinhvien" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ngay" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="soluong" Type="System.Int32" DbType="Int" />
    <Parameter Name="mucdich" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="donvimuon" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DAPANKHAOSAT_add" Method="DAPANKHAOSAT_add">
    <Parameter Name="madapankhaosat" Type="System.Int32" DbType="Int" />
    <Parameter Name="makhaosat" Type="System.Int32" DbType="Int" />
    <Parameter Name="tieude" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DAPANKHAOSAT_delete" Method="DAPANKHAOSAT_delete">
    <Parameter Name="madapankhaosat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DAPANKHAOSAT_get" Method="DAPANKHAOSAT_get">
    <Parameter Name="madapankhaosat" Type="System.Int32" DbType="Int" />
    <ElementType Name="DAPANKHAOSAT_getResult">
      <Column Name="madapankhaosat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="makhaosat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DAPANKHAOSAT_getall" Method="DAPANKHAOSAT_getall">
    <ElementType Name="DAPANKHAOSAT_getallResult">
      <Column Name="madapankhaosat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="makhaosat" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DAPANKHAOSAT_getpaged" Method="DAPANKHAOSAT_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DAPANKHAOSAT_update" Method="DAPANKHAOSAT_update">
    <Parameter Name="madapankhaosat" Type="System.Int32" DbType="Int" />
    <Parameter Name="makhaosat" Type="System.Int32" DbType="Int" />
    <Parameter Name="tieude" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GIOITHIEU_add" Method="GIOITHIEU_add">
    <Parameter Name="magioithieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="tengioithieu" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="noidung" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GIOITHIEU_delete" Method="GIOITHIEU_delete">
    <Parameter Name="magioithieu" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GIOITHIEU_get" Method="GIOITHIEU_get">
    <Parameter Name="magioithieu" Type="System.Int32" DbType="Int" />
    <ElementType Name="GIOITHIEU_getResult">
      <Column Name="magioithieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tengioithieu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.GIOITHIEU_getall" Method="GIOITHIEU_getall">
    <ElementType Name="GIOITHIEU_getallResult">
      <Column Name="magioithieu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tengioithieu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.GIOITHIEU_getpaged" Method="GIOITHIEU_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GIOITHIEU_update" Method="GIOITHIEU_update">
    <Parameter Name="magioithieu" Type="System.Int32" DbType="Int" />
    <Parameter Name="tengioithieu" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="noidung" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HETHONGTOCHUC_add" Method="HETHONGTOCHUC_add">
    <Parameter Name="mahethongtochuc" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenhethongtochuc" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="noidung" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HETHONGTOCHUC_delete" Method="HETHONGTOCHUC_delete">
    <Parameter Name="mahethongtochuc" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HETHONGTOCHUC_get" Method="HETHONGTOCHUC_get">
    <Parameter Name="mahethongtochuc" Type="System.Int32" DbType="Int" />
    <ElementType Name="HETHONGTOCHUC_getResult">
      <Column Name="mahethongtochuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenhethongtochuc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.HETHONGTOCHUC_getall" Method="HETHONGTOCHUC_getall">
    <ElementType Name="HETHONGTOCHUC_getallResult">
      <Column Name="mahethongtochuc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenhethongtochuc" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.HETHONGTOCHUC_getpaged" Method="HETHONGTOCHUC_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HETHONGTOCHUC_update" Method="HETHONGTOCHUC_update">
    <Parameter Name="mahethongtochuc" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenhethongtochuc" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="noidung" Type="System.String" DbType="NText" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HINHANH_add" Method="HINHANH_add">
    <Parameter Name="mahinhanh" Type="System.Int32" DbType="Int" />
    <Parameter Name="hinhanh" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="maalbum" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HINHANH_delete" Method="HINHANH_delete">
    <Parameter Name="mahinhanh" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HINHANH_get" Method="HINHANH_get">
    <Parameter Name="mahinhanh" Type="System.Int32" DbType="Int" />
    <ElementType Name="HINHANH_getResult">
      <Column Name="mahinhanh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhanh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="maalbum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.HINHANH_getall" Method="HINHANH_getall">
    <ElementType Name="HINHANH_getallResult">
      <Column Name="mahinhanh" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="hinhanh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="maalbum" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.HINHANH_getpaged" Method="HINHANH_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HINHANH_update" Method="HINHANH_update">
    <Parameter Name="mahinhanh" Type="System.Int32" DbType="Int" />
    <Parameter Name="hinhanh" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="maalbum" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HOATDONG_add" Method="HOATDONG_add">
    <Parameter Name="mahoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenhoatdong" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ngaydienra" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="maloaihoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="thoigianbatdaudangky" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="thoigianketthucdangky" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HOATDONG_delete" Method="HOATDONG_delete">
    <Parameter Name="mahoatdong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HOATDONG_get" Method="HOATDONG_get">
    <Parameter Name="mahoatdong" Type="System.Int32" DbType="Int" />
    <ElementType Name="HOATDONG_getResult">
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenhoatdong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ngaydienra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maloaihoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoigianbatdaudangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thoigianketthucdangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.HOATDONG_getall" Method="HOATDONG_getall">
    <ElementType Name="HOATDONG_getallResult">
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenhoatdong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ngaydienra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="maloaihoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="thoigianbatdaudangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thoigianketthucdangky" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.HOATDONG_getpaged" Method="HOATDONG_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HOATDONG_update" Method="HOATDONG_update">
    <Parameter Name="mahoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenhoatdong" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ngaydienra" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="maloaihoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="thoigianbatdaudangky" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="thoigianketthucdangky" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KHAOSAT_add" Method="KHAOSAT_add">
    <Parameter Name="macauhoi" Type="System.Int32" DbType="Int" />
    <Parameter Name="masinhvien" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="madapan" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KHAOSAT_delete" Method="KHAOSAT_delete">
    <Parameter Name="macauhoi" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KHAOSAT_get" Method="KHAOSAT_get">
    <Parameter Name="macauhoi" Type="System.Int32" DbType="Int" />
    <ElementType Name="KHAOSAT_getResult">
      <Column Name="macauhoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="madapan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.KHAOSAT_getall" Method="KHAOSAT_getall">
    <ElementType Name="KHAOSAT_getallResult">
      <Column Name="macauhoi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="masinhvien" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="madapan" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.KHAOSAT_getpaged" Method="KHAOSAT_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.KHAOSAT_update" Method="KHAOSAT_update">
    <Parameter Name="macauhoi" Type="System.Int32" DbType="Int" />
    <Parameter Name="masinhvien" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="madapan" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LICHLAMVIEC_add" Method="LICHLAMVIEC_add">
    <Parameter Name="noidung" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LICHLAMVIEC_delete" Method="LICHLAMVIEC_delete">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LICHLAMVIEC_get" Method="LICHLAMVIEC_get">
    <ElementType Name="LICHLAMVIEC_getResult">
      <Column Name="noidung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LICHLAMVIEC_getall" Method="LICHLAMVIEC_getall">
    <ElementType Name="LICHLAMVIEC_getallResult">
      <Column Name="noidung" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LICHLAMVIEC_getpaged" Method="LICHLAMVIEC_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LICHLAMVIEC_update" Method="LICHLAMVIEC_update">
    <Parameter Name="noidung" Type="System.String" DbType="NVarChar(1000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIBAIVIET_add" Method="LOAIBAIVIET_add">
    <Parameter Name="maloaibaiviet" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenloaibaiviet" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="machuyenmuc" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIBAIVIET_delete" Method="LOAIBAIVIET_delete">
    <Parameter Name="maloaibaiviet" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIBAIVIET_get" Method="LOAIBAIVIET_get">
    <Parameter Name="maloaibaiviet" Type="System.Int32" DbType="Int" />
    <ElementType Name="LOAIBAIVIET_getResult">
      <Column Name="maloaibaiviet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenloaibaiviet" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="machuyenmuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LOAIBAIVIET_getall" Method="LOAIBAIVIET_getall">
    <ElementType Name="LOAIBAIVIET_getallResult">
      <Column Name="maloaibaiviet" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenloaibaiviet" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="machuyenmuc" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LOAIBAIVIET_getpaged" Method="LOAIBAIVIET_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIBAIVIET_update" Method="LOAIBAIVIET_update">
    <Parameter Name="maloaibaiviet" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenloaibaiviet" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="machuyenmuc" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIHOATDONG_add" Method="LOAIHOATDONG_add">
    <Parameter Name="maloaihoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenloaihoatdong" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIHOATDONG_delete" Method="LOAIHOATDONG_delete">
    <Parameter Name="maloaihoatdong" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIHOATDONG_get" Method="LOAIHOATDONG_get">
    <Parameter Name="maloaihoatdong" Type="System.Int32" DbType="Int" />
    <ElementType Name="LOAIHOATDONG_getResult">
      <Column Name="maloaihoatdong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenloaihoatdong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LOAIHOATDONG_getall" Method="LOAIHOATDONG_getall">
    <ElementType Name="LOAIHOATDONG_getallResult">
      <Column Name="maloaihoatdong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenloaihoatdong" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LOAIHOATDONG_getpaged" Method="LOAIHOATDONG_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIHOATDONG_update" Method="LOAIHOATDONG_update">
    <Parameter Name="maloaihoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenloaihoatdong" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIVAITRO_add" Method="LOAIVAITRO_add">
    <Parameter Name="maloaivaitro" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenloaivaitro" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIVAITRO_delete" Method="LOAIVAITRO_delete">
    <Parameter Name="maloaivaitro" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIVAITRO_get" Method="LOAIVAITRO_get">
    <Parameter Name="maloaivaitro" Type="System.Int32" DbType="Int" />
    <ElementType Name="LOAIVAITRO_getResult">
      <Column Name="maloaivaitro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenloaivaitro" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LOAIVAITRO_getall" Method="LOAIVAITRO_getall">
    <ElementType Name="LOAIVAITRO_getallResult">
      <Column Name="maloaivaitro" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tenloaivaitro" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LOAIVAITRO_getpaged" Method="LOAIVAITRO_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.LOAIVAITRO_update" Method="LOAIVAITRO_update">
    <Parameter Name="maloaivaitro" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenloaivaitro" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SINHVIEN_add" Method="SINHVIEN_add">
    <Parameter Name="masinhvien" Type="System.Int32" DbType="Int" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="vaitro" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SINHVIEN_delete" Method="SINHVIEN_delete">
    <Parameter Name="masinhvien" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SINHVIEN_get" Method="SINHVIEN_get">
    <Parameter Name="masinhvien" Type="System.Int32" DbType="Int" />
    <ElementType Name="SINHVIEN_getResult">
      <Column Name="masinhvien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="vaitro" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SINHVIEN_getall" Method="SINHVIEN_getall">
    <ElementType Name="SINHVIEN_getallResult">
      <Column Name="masinhvien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="hoten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="vaitro" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SINHVIEN_getpaged" Method="SINHVIEN_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SINHVIEN_update" Method="SINHVIEN_update">
    <Parameter Name="masinhvien" Type="System.Int32" DbType="Int" />
    <Parameter Name="pass" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="vaitro" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TAPTIN_add" Method="TAPTIN_add">
    <Parameter Name="mataptin" Type="System.Int32" DbType="Int" />
    <Parameter Name="tentaptin" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="duongdan" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="mabaiviet" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TAPTIN_delete" Method="TAPTIN_delete">
    <Parameter Name="mataptin" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TAPTIN_get" Method="TAPTIN_get">
    <Parameter Name="mataptin" Type="System.Int32" DbType="Int" />
    <ElementType Name="TAPTIN_getResult">
      <Column Name="mataptin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tentaptin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="duongdan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="mabaiviet" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TAPTIN_getall" Method="TAPTIN_getall">
    <ElementType Name="TAPTIN_getallResult">
      <Column Name="mataptin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tentaptin" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="duongdan" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="mabaiviet" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.TAPTIN_getpaged" Method="TAPTIN_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.TAPTIN_update" Method="TAPTIN_update">
    <Parameter Name="mataptin" Type="System.Int32" DbType="Int" />
    <Parameter Name="tentaptin" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="duongdan" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="mabaiviet" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THONGBAO_add" Method="THONGBAO_add">
    <Parameter Name="mathongbao" Type="System.Int32" DbType="Int" />
    <Parameter Name="tieude" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="noidung" Type="System.String" DbType="NText" />
    <Parameter Name="mahoatdong" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaydang" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THONGBAO_delete" Method="THONGBAO_delete">
    <Parameter Name="mathongbao" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.THONGBAO_get" Method="THONGBAO_get">
    <Parameter Name="mathongbao" Type="System.Int32" DbType="Int" />
    <ElementType Name="THONGBAO_getResult">
      <Column Name="mathongbao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.THONGBAO_getall" Method="THONGBAO_getall">
    <ElementType Name="THONGBAO_getallResult">
      <Column Name="mathongbao" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tieude" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="noidung" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="mahoatdong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngaydang" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.THONGBAO_getpaged" Method="THONGBAO_getpaged">
    <Parameter Name="WhereClause" Parameter="whereClause" Type="System.String" DbType="NVarChar(4000)" />
    <Parameter Name="OrderBy" Parameter="orderBy" Type="System.String" DbType="VarChar(2000)" />
    <Parameter Name="PageIndex" Parameter="pageIndex" Type="System.Int32" DbType="Int" />
    <Parameter Name="PageSize" Parameter="pageSize" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>