//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTOAuction.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\webdoantruong.mdf;Integ" +
            "rated Security=True;User Instance=True")]
        public string webdoantruongConnectionString {
            get {
                return ((string)(this["webdoantruongConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MANTERO-81F34CE\\SQLEXPRESS;Initial Catalog=webdoantruong;Integrated S" +
            "ecurity=True")]
        public string webdoantruongConnectionString1 {
            get {
                return ((string)(this["webdoantruongConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\WebDoanHoi_layout\\WebDoanHoi_layout\\" +
            "WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=True;User Insta" +
            "nce=True")]
        public string webdoantruongConnectionString2 {
            get {
                return ((string)(this["webdoantruongConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\WebDoanHoi_vpm_2907\\WebDoanH" +
            "oi_layout\\WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=True;" +
            "User Instance=True")]
        public string webdoantruongConnectionString3 {
            get {
                return ((string)(this["webdoantruongConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=e:\\_Tong_hop_project\\Web_Doan-Hoi_Proje" +
            "ct\\WebDoanHoi_vpm_2907\\WebDoanHoi_layout\\WebDoanHoi_layout\\App_Data\\webdoantruon" +
            "g.mdf;Integrated Security=True;User Instance=True")]
        public string webdoantruongConnectionString4 {
            get {
                return ((string)(this["webdoantruongConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\Rap_HMinh\\WebDoanHoi_vpm_310" +
            "7\\WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=True;User Ins" +
            "tance=True")]
        public string webdoantruongConnectionString5 {
            get {
                return ((string)(this["webdoantruongConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=NN;Initial Catalog=D:\\MHX2010\\RAP_HMINH\\WEBDOANHOI_VPM_3107\\WEBDOANHO" +
            "I_LAYOUT\\APP_DATA\\WEBDOANTRUONG.MDF;Integrated Security=True")]
        public string D__MHX2010_RAP_HMINH_WEBDOANHOI_VPM_3107_WEBDOANHOI_LAYOUT_APP_DATA_WEBDOANTRUONG_MDFConnectionString {
            get {
                return ((string)(this["D__MHX2010_RAP_HMINH_WEBDOANHOI_VPM_3107_WEBDOANHOI_LAYOUT_APP_DATA_WEBDOANTRUONG" +
                    "_MDFConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\Rap_HMinh_2\\Rap_HMinh\\WebDoa" +
            "nHoi_vpm_3107\\WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=T" +
            "rue;User Instance=True")]
        public string webdoantruongConnectionString6 {
            get {
                return ((string)(this["webdoantruongConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\Rap_HMinh_2\\Rap_HMinh\\WebDoa" +
            "nHoi_vpm_0408\\WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=T" +
            "rue;User Instance=True")]
        public string webdoantruongConnectionString7 {
            get {
                return ((string)(this["webdoantruongConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\WebDoanTruong_0408\\Rap_HMinh" +
            "\\WebDoanHoi_vpm_0408\\WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Sec" +
            "urity=True;User Instance=True")]
        public string webdoantruongConnectionString8 {
            get {
                return ((string)(this["webdoantruongConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\WebDoanTruong_0508\\Rap_HMinh" +
            "\\WebDoanHoi_vpm_0408\\WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Sec" +
            "urity=True;User Instance=True")]
        public string webdoantruongConnectionString9 {
            get {
                return ((string)(this["webdoantruongConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\WebDoanHoi_vpm_0508\\WebDoanH" +
            "oi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=True;User Instance=True" +
            "")]
        public string webdoantruongConnectionString10 {
            get {
                return ((string)(this["webdoantruongConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\WebDoanHoi_vpm_1208\\WebDoanH" +
            "oi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=True;User Instance=True" +
            "")]
        public string webdoantruongConnectionString11 {
            get {
                return ((string)(this["webdoantruongConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"D:\\EBOOK\\Projects Trung Nghia\\Web\\New " +
            "folder\\WebDoanHoi_layout\\App_Data\\webdoantruong.mdf\";Integrated Security=True;Us" +
            "er Instance=True")]
        public string webdoantruongConnectionString12 {
            get {
                return ((string)(this["webdoantruongConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\WebDoanHoi_vpm_1708\\WebDoanHoi_layou" +
            "t\\App_Data\\webdoantruong.mdf;Integrated Security=True;User Instance=True")]
        public string webdoantruongConnectionString13 {
            get {
                return ((string)(this["webdoantruongConnectionString13"]));
            }
        }
    }
}
