//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTOAuction.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=|DataDirectory|\\webdoantruong.mdf;Integ" +
            "rated Security=True;User Instance=True")]
        public string webdoantruongConnectionString {
            get {
                return ((string)(this["webdoantruongConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MANTERO-81F34CE\\SQLEXPRESS;Initial Catalog=webdoantruong;Integrated S" +
            "ecurity=True")]
        public string webdoantruongConnectionString1 {
            get {
                return ((string)(this["webdoantruongConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\WebDoanHoi_layout\\WebDoanHoi_layout\\" +
            "WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=True;User Insta" +
            "nce=True")]
        public string webdoantruongConnectionString2 {
            get {
                return ((string)(this["webdoantruongConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=D:\\MHX2010\\WebDoanHoi_vpm_2907\\WebDoanH" +
            "oi_layout\\WebDoanHoi_layout\\App_Data\\webdoantruong.mdf;Integrated Security=True;" +
            "User Instance=True")]
        public string webdoantruongConnectionString3 {
            get {
                return ((string)(this["webdoantruongConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=e:\\_Tong_hop_project\\Web_Doan-Hoi_Proje" +
            "ct\\WebDoanHoi_vpm_2907\\WebDoanHoi_layout\\WebDoanHoi_layout\\App_Data\\webdoantruon" +
            "g.mdf;Integrated Security=True;User Instance=True")]
        public string webdoantruongConnectionString4 {
            get {
                return ((string)(this["webdoantruongConnectionString4"]));
            }
        }
    }
}
